version: '3.9'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: umrobotics/curly_slam:latest
    entrypoint: /bin/zsh
    command: -c "source /opt/ros/melodic/setup.zsh && stdbuf -o L roscore"
    networks:
      - ros
    restart: always
    container_name: ros-master

  slam:
    image: umrobotics/curly_slam:latest
    container_name: slam
    networks:
      - ros
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_GRAPHICSSYSTEM=native"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "TERM=xterm-256color"
      - "XAUTHORITY"
    working_dir: "/home/${USER}/ws/"
    privileged: true
    devices:
      - /dev/nvidia0
      - /dev/nvidia-modeset
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - .zshrc:/home/${USER}/.zshrc:rw
      - .zsh_history:/home/${USER}/.zsh_history:rw
      - /home/$USER/Projects/bnb-icp/:/home/${USER}/ws/
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    entrypoint: /bin/zsh
